### ISSUE TITLE
configtest.pl reports "upgrade required" when using mariadb 10

### ISSUE THREAD

**Issue by geirvn** [technion/maia_mailguard#21]
configtest.pl should be able to check whether you are running mariadb or mysql and report error / min version based on that.

**Comment by technion** [comment]
Can you get a copy of the exact message and which test is failing please?

What distribution is this, I haven't run into MariaDB 10 in the wild yet.

Either way, I think the sanest thing to do is remove the test altogether. The minimum version supported was originally 5.0, I don't believe I've done anything to increase that, and I don't see a need to worry about anyone deploying new spam filters with versions older than that.

I'll note configtest.php actually discusses there being no required MySQL version.

**Comment by geirvn** [comment]
I agree that the "db version" test is unnecessary, and can be removed.

Distribution: 
Ubuntu 14.0.4 LTS

mariadb:
+------------------------------+
| version()                    |
+------------------------------+
| 10.0.16-MariaDB-1~trusty-log |
+------------------------------+

Output from configtest.pl:
MySQL Server           :  10.0.16 : UPGRADE REQUIRED (minimum version 5.0.0)

**Comment by technion** [comment]
I've spent a bit of time looking into this and to be blunt, I have no idea why 10.0.16 would report itself as lower than the required version 5.0.0. It didn't take long until that feel into the "too hard" basket.

I've pushed a commit to configtest.pl that removes the minimum MySQL version. The reality is that any system that meets the PHP requirements is going to be recent enough on the MySQL front.

**Comment by geirvn** [comment]
I agree with you, the db version is not relevant. 

But anyway; I have done some testing:
It seems that perl reads 10 as 1, 40 as 4, 50 as 5 and so on:

On line 384, set $dbversion manually:
 $dbversion = "5.0.1";  ##Success.
 $dbversion = "9.9.9";  ##Success.
 $dbversion = "50.0.1";  ##Success.
 $dbversion = "40.9.9";  ##Fail.
 $dbversion = "10.0.0";  ##Fail.
