### ISSUE TITLE
missing theme/*/compile dir

### ISSUE THREAD

**Issue by jstr33t** [technion/maia_mailguard#26]
I am currently testing the setup of this fork.

When I run https://server/maia/admin/configtest.php  it complains of file permission errors and recommends reading [Blank Page](http://www.maiamailguard.com/maia/wiki/BlankPage).

The first thing it suggests doing it making sure that the `theme/*/compile` directories are writable by web server.   

Looking in` /var/www/maia/themes/*/`  based on this fork it turns out there are no `compile` directories included.  Looking at Maia 1.0.2c  the `compile` folder is included as part of the archive.

The error can be removed by creating the 3 `compile` directories and `chown www-data.` the directories.

**Comment by technion** [comment]
Unfortunately there is a fundamental problem here - git silently drops empty directories. I don't want to create a useless file just to work around it. I'll note the requirement to actually create these directories in the wiki.
