### ISSUE TITLE
Is there a need for two SHA perl modules?

### ISSUE THREAD

**Issue by jstr33t** [technion/maia_mailguard#28]
From the `configtest.pl` I see that there are now two SHA perl libraries needed

    Digest::SHA
    Digest::SHA1 (used by razor)

Under Ubuntu Digest::SHA is met by package `libdigest-sha-perl` but there is nothing for Digest::SHA1, though it can be installed via `perl -MCPAN -e shell`

Are both actually needed?  Based on CPAN, Digest::SHA does SHA1 which at least superficially in my mind makes the need for Digest::SHA1 redundant.

**Comment by technion** [comment]
Unfortunately, this is genuine.

The maia code itself uses Digest:SHA. This is from its legacy as amavis, which used Digest::SHA.

Razor is documented as requiring Digest::SHA1. Razor is a third party module not installed or used by default, so you could well skip this step and avoid that requirement if you have not installed Razor.

Razor itself will happily let you know it's not working if you have not met the requirement.
