### ISSUE TITLE
Making use of releases

### ISSUE THREAD

**Issue by jstr33t** [technion/maia_mailguard#30]
Would it be possible to make use of [releases](https://github.com/technion/maia_mailguard/releases) on the github so that we can easily download an archive for a particular version.

At the moment users would be reliant on downloading the `master` archive which could result in them downloading a buggy version as changes get made.

**Comment by technion** [comment]
For the foreseeable future, every code change made is a bugfix. If the concern is "a buggy version", I would recommend utilising master, rather than an arbitrarily tagged release.
