### ISSUE TITLE
--tempdir for clamscan not being set correctly

### ISSUE THREAD

**Issue by jstr33t** [technion/maia_mailguard#33]
I ran into an issue with maia_mailguard 1.0.4 on ubuntu 12.04 (php5.3.10) and clamav 0.98.7.

When maiad started to try and process emails it was failing with the following error

    /usr/sbin/maiad[2460]: (02460-07) TROUBLE in check_mail: virus_scan FAILED: virus_scan: ALL VIRUS SCANNERS FAILED: ClamAV-clamscan av-scanner FAILED: /usr/bin/clamscan unexpected exit 2, output="ERROR: Option --tempdir requires a non-empty string argument\nERROR: Can't parse command line options" at (eval 82) line 424.

As a work around I updated line [416](https://github.com/technion/maia_mailguard/blob/master/maiad.conf.dist#L416) in `/etc/maia/maiad.conf` hardcoding `--tempdir=$TEMPBASE` to `--tempdir=/var/lib/maia/tmp`, which is where I believe $TEMPBASE is supposed to be.  After that maia_mailguard was able to process mail again.

**Comment by technion** [comment]
Thanks for reporting this. I can't recommend highly enough using the clamd scanning daemon over the command line version - this would be why I hadn't noted it earlier.

TEMPBASE doesn't appear to be defined anywhere so I will get that fixed.
