### ISSUE TITLE
X-Spam-Status not showing autolearn part

### ISSUE THREAD

**Issue by blackcobra1973** [technion/maia_mailguard#35]
Hello All,

I am missing the autolearn part from the X-Spam header.  Also this value is not available at the moment the SQL insert is happening, which causes a failure due to the NOT NULL constraint.  

I have disabled at the moment the NOT NULL constraint.  

###### Example found in my maillog with a higher log detail: 
Jun  8 16:25:32 xxxxxx maiad[13222]: (13222-01) spam_scan: hits=0.315 tests=AWL=0.424,DKIM_SIGNED=0.1,DKIM_VALID=-0.1,DKIM_VALID_AU=-0.1,HTML_MESSAGE=0.001,T_RP_MATCHES_RCVD=-0.01 autolearn=ham autolearn_force=no

######  Example output
Subject: Test
Message-Id: <20150608143659.7F51E4B@xxxxxxxxxxxxx>
Date: Mon,  8 Jun 2015 16:36:59 +0200 (CEST)
From: root@xxxxxxxxxx (root xxxxxxx)
X-Virus-Scanned: Maia Mailguard 1.0.4
X-Spam-Status: No, hits=-0.987 tagged_above=-100 required=5 tests=AWL=-0.986,
 NO_RELAYS=-0.001
X-Spam-Level: 

As you notice the information is not in the final header.

**Comment by technion** [comment]
Can you confirm which constraint you disabled? I'd like to commit this fix to the original SQL.

**Comment by blackcobra1973** [comment]
I need to check again, I made some changes also in the code to actually make it work, or put the default  value in it.   I will fork the project and provide in this way the patch if that is ok ?

**Comment by technion** [comment]
Thank you for the PR, I have merged it.
