### ISSUE TITLE
Smarty3 Errors When Accessing Certain Pages

### ISSUE THREAD

**Issue by Munk3y** [technion/maia_mailguard#37]
Ubuntu 14.04.3 x64
PHP 5.5.9
Smarty 3.1.13
Maia Mailguard 1.0.4 (cloned on 08/17/15)

Most of the Maia Mailguard interface seems to work properly but accessing some pages, the Stats page or the Settings page for a Domain for example, produces the following error:

[Tue Aug 18 13:38:45.485292 2015] [:error] [pid 2247] [client 10.0.20.10:55664] PHP Fatal error:  Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template &quot;/var/www/mail/themes/ocean_surf/templates/settings/_address.tpl&quot;  on line 78 &quot;&amp;lt;input type=text size=7 name=level1 value=&amp;quot;{$level1|string_format:&amp;quot;%1.3f&amp;quot;}&amp;quot;&amp;gt;&quot; unknown modifier &quot;string_format&quot;' in /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php:665\nStack trace:\n#0 /usr/share/php/smarty3/sysplugins/smarty_internal_compile_private_modifier.php(132): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown modifie...', 78)\n#1 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(483): Smarty_Internal_Compile_Private_Modifier->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler), Array, NULL, NULL)\n#2 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(257): Smarty_Internal_TemplateCompilerBase->callTagCompiler('private_modifie...', Array, Array)\n#3 /usr/share/php in /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php on line 665, referer: http://10.0.20.191/welcome.php

**Comment by technion** [comment]
Thank you for logging this issue. I have been unable to replicate this, however, there was a previous mailing list report from David Byte with the exact same error, stating:

I fixed the Smarty error, it was the library path.. 

Does this help?

**Comment by adikaram** [comment]
Do u have any installation steps?? i cant access this link.
http://www200.pair.com/mecham/spam/rhel5-maia.html

this is the error massage .. Forbidden

You don't have permission to access /mecham/spam/rhel5-maia.html on this server.

**Comment by Munk3y** [comment]
@technion - Thanks, I will look into that more and report back.

@adikaram - I am trying to get instructions completed at the link below. I have another revision of the script coming soon and also need to find a place to host the maia_files.tar.gz archive that's needed by the script.

https://github.com/technion/maia_mailguard/wiki/Ubuntu-14.04-&-Maia-Mailguard-1.0.4-Installation-Instructions

**Comment by adikaram** [comment]
sir do u have script for centos..

**Comment by Munk3y** [comment]
@adikaram Unfortunately, I don't :( I use Ubuntu Server mostly and so I'm focused on just getting it up and running there for the moment.

**Comment by technion** [comment]
@adikaram  stop spamming multiple tickets with this request. I've already provided you a link to the official guide.

**Comment by Munk3y** [comment]
I have not been able to resolve this. :( All library paths appear to be correct and accessible. I'll continue troubleshooting but if anyone has an idea, I'd love to hear it. Thanks!

**Comment by Marco-ITSM** [comment]
Hi Munk3y,

ugly fix, but the problem can be resolved by installing Smarty2...

`cd`
`wget http://www.smarty.net/files/Smarty-2.6.27.tar.gz`
`cd /usr/share/php/`
`tar xzf ~/Smarty-2.6.27.tar.gz`
`chown -R root:root Smarty-2.6.27`
`rm Smarty`
`ln -s Smarty-2.6.27/libs Smarty`

**Comment by dcortez** [comment]
Found the issue for these errors. Basically, since smarty3 you can no longer access the $plugins_dir var directly and instead need to use addPluginsDir($array/$string) or setPluginsDir($array/$string) -- pulled from their website. So in smarty.php change the following...

From:
`            if (!empty($spath)) {
                $this->plugins_dir = array($this->_basedir.'code/', $spath . '/plugins');
            } else {
                $this->plugins_dir = array($this->_basedir.'code/', "Smarty/plugins");
            }`

To:
`            if (!empty($spath)) {
                $this->addPluginsDir(array($spath . '/plugins', $this->_basedir.'code/'));
            } else {
                $this->addPluginsDir(array($this->_basedir.'code/'));
            }`

The other issue I noticed is the second line was actually overwriting the plugins directory for smarty. So simply remove "Smarty/plugins" from the array after making the changes noted.

Hope this helps.

**Comment by technion** [comment]
That's a great find. If you can make a PR I'll merge it and happily close this off.

**Comment by dcortez** [comment]
Done: #45

**Comment by technion** [comment]
Closed in #45 .
