### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by adikaram** [technion/maia_mailguard#38]
Do u have any installation steps?? i cant access this link.
http://www200.pair.com/mecham/spam/rhel5-maia.html

this is the error massage .. Forbidden

You don't have permission to access /mecham/spam/rhel5-maia.html on this server.

**Comment by technion** [comment]
I have no idea where that link came from and don't have anything to do with its content.

The last official documentation predates this fork, but is still able to get you running:

http://www.maiamailguard.com/maia/wiki/Install

**Comment by adikaram** [comment]
no sir, User-Contributed Documentation section not working..

**Comment by technion** [comment]
I do agree that some of the user contributed documents linked from that page are no longer valid. Most of them are however.

You could alternatively stick to the documentation on the page itself.
