### ISSUE TITLE
Mails which are deleted do not get cleaned up in Database

### ISSUE THREAD

**Issue by blackcobra1973** [technion/maia_mailguard#41]
Incident description:  I deleted some mails in the web GUI but for some reason they stay in the database.

Some output: 
```sql
maia=# select * from maia_mail_recipients;
 mail_id | recipient_id | type | token
---------+--------------+------+-------
(0 rows)

maia=# select id,received_date,sender_email,score,autolearn_status from maia_mail;
   id   |       received_date        |     sender_email      | score  | autolearn_status
--------+----------------------------+-----------------------+--------+------------------
 382822 | 2015-10-11 14:02:03.356713 | root@  | -3.071 | ham
 382708 | 2015-10-10 18:28:27.205804 | kdillen@     |  1.182 | no
 382713 | 2015-10-10 19:09:58.464287 | kdillen@     |  1.728 | no
 382725 | 2015-10-10 22:55:21.975898 | root@  | -3.074 | ham
 382697 | 2015-10-10 15:19:16.463165 | kdillen77@ | -0.117 | ham
 382699 | 2015-10-10 17:16:34.960262 | kdillen77@ | -0.237 | ham
 382716 | 2015-10-10 20:05:16.434559 | kdillen@     |  1.215 | no
 382712 | 2015-10-10 19:08:35.682478 | kdillen77@ | -0.298 | ham
 382823 | 2015-10-11 14:19:25.805396 | root@  | -3.071 | ham
 382746 | 2015-10-11 00:59:44.839002 | root@  | -3.073 | ham
 382829 | 2015-10-11 15:35:09.479548 | root@  | -3.071 | ham
 382802 | 2015-10-11 09:23:18.833298 | root@  | -3.071 | ham
(12 rows)
```
As you see above there are still mail records but the links with the recipients do not exists anymore, in the long term this means or on busy systems a lot of dummy records stay in the tables.

**Comment by technion** [comment]
Have you run the maintenance scripts? 

http://www.maiamailguard.com/maia/wiki/Install

Step 19.

Do those scripts produce any errors?

**Comment by blackcobra1973** [comment]
ok, I found out this is done by the /var/amavis/maia/scripts/expire-quarantine-cache.pl script, and I am only running this 1 times a week.  That explains all.  

You can close the ticket.

**Comment by technion** [comment]
For what it's worth I recommend daily on that script  - running it weekly on some of my systems meant running it for something like nine hours.
