### ISSUE TITLE
scan Office 2007 XML-based files

### ISSUE THREAD

**Issue by ulf1** [technion/maia_mailguard#43]
Hello I uploaded a modified version of your detectvba.pl because sigtool cannot process xlsx, docx, etc. directly. You need to unzip these XML files.

https://github.com/ulf1/maia_mailguard/blob/master/scripts/detectvba-xml.pl

**Comment by technion** [comment]
Your modified file contains a temp file symlink vulnerability, and I won't be able to merge it "as is".

I'll seek an alternative.

**Comment by ulf1** [comment]
yes i do not like it either. 
<pre>
sigtool --vba="vbafile"
</pre>
i could not figure out how to pipe directly into "vbafile". sigtool expect a FILE.

i tried the following
<pre>
myfilename="lalilu.xlsx"
sigtool --vba=$(unzip -p "$myfilename" "xl/vbaProject.bin")
</pre>
and
<pre>
myfilename="lalilu.xlsx"
unzip -p "$myfilename" "xl/vbaProject.bin" | sigtool --vba-hex=$(< /dev/stdin)
</pre>

i always get somthing like 
<pre>
ERROR: vbadump: Can't open file ��ࡱ�>��
</pre>

**Comment by ulf1** [comment]
i changed the perl script. it is using mkstemp for tempory file generation now.
