### ISSUE TITLE
Problem with Smarty3 string_format

### ISSUE THREAD

**Issue by Marco-ITSM** [technion/maia_mailguard#44]
Hi,

I just installed a new instance of Maia 1.0.4 under Ububuntu 14.04. So far so good... The Install Script was flawless except for the maia_files.tar.gz... But I got around that.

The [Problem with Smarty3](https://github.com/technion/maia_mailguard/wiki/Ubuntu-14.04-&-Maia-Mailguard-1.0.4-Installation-Instructions) also affected me i.e when accessing the settings page as a "domain" user (.@domain.tld). The error logged in the Apache Error Log is:

`[Wed Apr 20 14:47:41.189642 2016] [:error] [pid 2520] [client 172.26.17.124:54532] PHP Fatal error:  Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template &quot;/var/www/mail/themes/ocean_surf/templates/settings/_address.tpl&quot;  on line 78 &quot;&amp;lt;input type=text size=7 name=level1 value=&amp;quot;{$level1|string_format:&amp;quot;%.3f&amp;quot;}&amp;quot;&amp;gt;&quot; unknown modifier &quot;string_format&quot;' in /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php:665\nStack trace:\n#0 /usr/share/php/smarty3/sysplugins/smarty_internal_compile_private_modifier.php(132): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown modifie...', 78)\n#1 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(483): Smarty_Internal_Compile_Private_Modifier->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler), Array, NULL, NULL)\n#2 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(257): Smarty_Internal_TemplateCompilerBase->callTagCompiler('private_modifie...', Array, Array)\n#3 /usr/share/php/ in /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php on line 665`

In the file /var/www/mail/themes/ocean_surf/templates/settings/_address.tpl on lines 78, 85 and 92 
`|string_format:"%1.3f"`
had to be removed - problem solved.

**Comment by dcortez** [comment]
Found the issue for these errors. Basically, since smarty3 you can no longer access the $plugins_dir var directly and instead need to use addPluginsDir($array/$string) or setPluginsDir($array/$string) -- pulled from their website. So in smarty.php change the following...

From:
`            if (!empty($spath)) {
                $this->**plugins_dir =** array($this->_basedir.'code/', $spath . '/plugins');
            } else {
                $this->**plugins_dir =** array($this->_basedir.'code/', "Smarty/plugins");
            }`
`            if (!empty($spath)) {
                $this->**addPluginsDir(**array($spath . '/plugins', $this->_basedir.'code/')**)**;
            } else {
                $this->**addPluginsDir(**array($this->_basedir.'code/')**)**;
            }`

The other issue I noticed is the second line was actually overwriting the plugins directory for smarty. So simply remove "Smarty/plugins" from the array after making the changes noted.

Hope this helps.

**Comment by derekatkins** [comment]
Looks like this change was merged into master -- is there any reason this issue remains open?

**Comment by dcortez** [comment]
I'm not sure why this is still open since it was merged. I would say to close it.

**Comment by derekatkins** [comment]
Indeed.  I don't have the privs to close this..
