### ISSUE TITLE
euid in confirm.php is not set

### ISSUE THREAD

**Issue by hexathos** [technion/maia_mailguard#47]
Hi,

if clicking a "confirm all" link in one of the status mails, which lead in my case to

`<domainwashere>/mail/confirm.php?id=70&euid=70&ts=2016-06-09%2000%3A00%3A01&token=<tokenwashere>&report_ham=true`

we get an error like 
`[Mon Jun 13 22:40:26.670741 2016] [:error] [pid 5603] [client <internal>] PHP Fatal error:  Call to undefined method MDB2_Error::fetchRow() in /var/www/html/confirm.php on line 131`
and a white page for the user

tracking it down, an unset $euid was passed to the query above the line.

caused by
```
        $select = "SELECT maia_mail.id " .
                  "FROM maia_mail, maia_mail_recipients " .
                  "WHERE maia_mail.id = maia_mail_recipients.mail_id " .
                  "AND maia_mail.received_date <= ? " .
                  "AND maia_mail_recipients.type = 'H' " .
                  "AND maia_mail_recipients.recipient_id = ?";
        $sth = $dbh->query($select, array($cutoff_date, $euid));
```

the query can't complete, so an unhandled error is thrown which results in a blank page for the user, not reporting mails as ham and the logline above.

**Comment by piwikjapan** [comment]
What the feck! Until now, no one has made a test.
Be careful when you click "confirm all". You will pass the point of no return.

**Comment by technion** [comment]
Yes @piwikjapan , one of the main differences between my fork and the original version, was that not one query in the original version checked its returns. There were only a few actual bugs, but I had to insert hundreds of tests to actually find them. Seems I missed this one.

**Comment by piwikjapan** [comment]
This is important work. As I watched the old patches for Japanese to 1.0.2, the author had a lot of troubles with Japanese mail header. I think you worked well, when I saw the new codes about mail header decorder. I thank you for published in gpl. Let's go further.
