### ISSUE TITLE
php7 and configtest.php

### ISSUE THREAD

**Issue by BruceSackett** [technion/maia_mailguard#60]
Running configtest.php on command line, received this error:
PHP Fatal error:  Uncaught Error: Call to undefined function eregi() in /srv/www/main/mailguard/admin/configtest.php:148

Fix was to change line 148 from:
   if (!eregi("^\..*$",$f) && $f!=='.' && $f!=='..'){
to:
   if (!preg_match("/^\..*$/",$f) && $f!=='.' && $f!=='..'){

**Comment by technion** [comment]
Hi,

This looks like a good fix - if you send a PR I'll merge it in.

**Comment by derekatkins** [comment]
Can this issue be closed now?

**Comment by BruceSackett** [comment]
Absolutely!  Sorry for not doing so earlier.
