### ISSUE TITLE
md5 is unsecure, deprecated hashing method ! That is very dangerous to use it !

### ISSUE THREAD

**Issue by njuhel** [technion/maia_mailguard#61]
md5 is the one of the oldest hashing method. 
**That is very dangerous to use it.**

Remember with dictionary and GPU, MD5 could be brute force in less than 1 minute. In cloud calculator (used in mass hack process), there is less.

The standard hashing method arrive with the 3rd genertion : **Keccak**. 
More information with hashing world standard : http://csrc.nist.gov/groups/ST/hash/sha-3/index.html

Considered the time to update tools, code, ..., the Keccak is just coming to be use a the new standard in differnet tools like php. But md5 must not be found in anycode or system since many years... 
Offical world standard have send recommends to remove md5 and sha1 capabilities in profit of SHA2 or SHA3. Cypher using MD5/SHA1 are still removed for standard cypher list.

A good method if keccak is not available is to use the SHA256, SHA384 or SHA512 algorithms.
To use it, use the hash function like that : hash('sha256', 'your text')

Keccak algorithm is available in PHP 7.1, so should upgrade to this release for security reason.
And remember that php5.6 will be end of life in 2017. PHP 5.5 is end since 21 Jul 2016. See this page for more information : http://php.net/eol.php

Indeed in the php 7.1 you will find the ARGON2 password processing who's considered as password standard processing. Using like that : password_hash('password', PASSWORD_ARGON2I);

For password hashing competition, more information here : https://password-hashing.net/

**Comment by technion** [comment]
Hi,

I would appreciate actually looking before screaming that something is "dangerous".

- [I am quite familiar with Argon2](https://github.com/P-H-C/phc-winner-argon2/commits/master?author=technion).
- [When I inherited this project, the first thing I did was change MD5 password storage to scrypt](https://github.com/technion/maia_mailguard/commit/e598a3f8b95842e0eea3f81d4b8e003d3d66b20e). I don't understand why I am being lectured on password storage.
- This resulted in a project fork that rolled back to MD5 password storage. I have no involvement in that and this is not the place to make complaints about it.
- There are a few inherited places MD5 is still used, like in cache busting filenames. I guess I would take a PR if someone writes it but this project has better places for me to invest time in than changing them.
- Did you just insist that a project should set PHP 7.1 as a minimum requirement? It was released *ten days ago*.
