### ISSUE TITLE
/var/log/maia/maiad.log - unable to write

### ISSUE THREAD

**Issue by BruceSackett** [technion/maia_mailguard#62]
Something odd has stopped sending log information to my maiad.log log file.  I have syslog off and everything apparently set right in /etc/maia/maiad.conf, and have tried multiple user/group/permission settings, to no avail.

It is currently set to user maia group root, 644, and I have a 0 byte file.  I've tried other combinations, no luck.  Unfortunately, I suck at Perl and am not sure what to look for with the logging code to see where this could be a problem.  Any ideas where to look or what info I could provide that might help pinpoint?

**Comment by technion** [comment]
Hi,

I've only run maia previously with DO_SYSLOG enabled so I'm somewhat grasping at straws.

Could you first make sure you don't have SELinux getting involved by reviewing /var/log/audit/audit.log ?

Failing that, *temporarily* set it chmod 777, so we know if it's permissions, or a software bug.

**Comment by BruceSackett** [comment]
I've actually tried the 777, no luck.  It does work at syslog, so I've just moved it over to that now, since everything else is golden.  Something to dig into if I ever get around to learning perl I guess :)
