### ISSUE TITLE
Odd one - Whitelist/Blacklist scan order

### ISSUE THREAD

**Issue by BruceSackett** [technion/maia_mailguard#64]
Is there an easy way to alter Maia to ALLOW from the whitelist before it BLOCKS from the blacklist?  I have an issue where I'd like to allow certain emails through a general address that I want to blacklist, if that makes sense.

**Comment by technion** [comment]
Unfortunately this would require the addition of new feature code. I am not adding any new features at this time.

**Comment by BruceSackett** [comment]
Gotcha.  I think I see where and roughly what I want to do.  If it actually works, I'll hook in the changes I make if you ever want them.

**Comment by BruceSackett** [comment]
Just a follow-up.  What I've found is that (of course) the @ default is last to be checked, preceded by @<domain>, preceded by <user>@<domain> - I've moved my blacklist entries to the @ default and the required whitelists to @<domain>, and naturally that works perfectly.
