### ISSUE TITLE
Unable to get internal-init.php to run

### ISSUE THREAD

**Issue by martinmain** [technion/maia_mailguard#67]
I am unable to get beyond the internal-init.php script and end up with error in apache  error.log

PHP Fatal error:  Call to undefined function: MDB2_Driver_mysql::raiseError(). in /usr/share/pear/MDB2.php on line 1936, referer: http://mmsys/maia/admin/internal-init.php

The php and perl test configuration scripts give no indication of any problem

**Comment by technion** [comment]
As with all these issues, it's hard to get to the bottom of without seeing the environment.
For a start, can you confirm your version of PHP and the distro you've installed on?

**Comment by martinmain** [comment]
Thanks for reply I managed to get things up and running using the beta versions of MDB2 and the associated driver

Sent from my iPhone

On Jul 31, 2017, at 07:14, technion <notifications@github.com <mailto:notifications@github.com> > wrote:

As with all these issues, it's hard to get to the bottom of without seeing the environment.
For a start, can you confirm your version of PHP and the distro you've installed on?
