### ISSUE TITLE
configtest.php says: FAILED: Could not connect to database. Check the mysql://test:testtest@tcp(localhost:3306)/maia setting in config.php. 

### ISSUE THREAD

**Issue by resiew** [technion/maia_mailguard#68]
Hey,
I am trying to get Maia to work on a Ubuntu 16.04.3 LTS installation. But I have trouble to get web part to connect to the database.
The configtest.php write out that it is not able to login to my database, I have tested the login information and they are correct. I might have missed something here, but I can't get around it. I cannot see anything on the apache error log file.

in config.php:
$maia_sql_dsn = "mysql://test:testtest@tcp(localhost:3306)/maia";

PHP version:
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Any suggestion or information needed?

Regards,

Kim

**Comment by pesselbach** [comment]
You need to use MySQLi after the older MySQL extension has been removed from the PHP 7.x series

This should do the trick:
$maia_sql_dsn = "mysqli://test:testtest@tcp(localhost:3306)/maia";

**Comment by resiew** [comment]
Thanks, that fixed it, I have made two PR to fix the configtest.php and the config.php. I hope it is correct done, because it is my first time to make one.
