### ISSUE TITLE
maiad reports: Column 'autolearn_status' cannot be null

### ISSUE THREAD

**Issue by resiew** [technion/maia_mailguard#71]
Hey,
When an email i send to my Maia it reports this error:
TROUBLE in check_mail: Take Action! FAILED: DBD::mysql::st execute failed: Column 'autolearn_status' cannot be null at /usr/local/sbin/maiad line 4410.

$autolearn_status is: "no autolearn_force=no" before this line:
line 4297 in maiad: $autolearn_status = validate($autolearn_status, '^([a-z]{2,15})$', 'si');
and after it is: ""

I guess I get the wrong information into the $autolearn_status. But I don't understand why, can anybody help me?

I'm running on Ubuntu 16.04.

Thanks, 

Kim

**Comment by mcrauwel** [comment]
Hi @resiew,

I've encountered the same problem a while ago. I fixed it for my installation back then. I've just created a PR (#72) to include my fix in the main repo... You can always test on your installation if my fix works for you and provide your feedback here!

**Comment by resiew** [comment]
Hey @mcrauwel,

I have tested it and it is working. Thanks for the help.

Kim
