### ISSUE TITLE
maiad warns for fetal errors in perl 5.32

### ISSUE THREAD

**Issue by Mofred1** [technion/maia_mailguard#79]
Dear All
I get following messages when I start maiad, but I can't find the lines in the file

Oct 15 12:29:39 Server2.horn systemd[1]: Starting LSB: Starts amavisd-maia maiad mailfilter...
Oct 15 12:29:40 Server2.horn amavis-maiad[18408]: Starting maiad: Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/ ({ <-- HERE }/)? \* / at (eval 109) line 304.
Oct 15 12:29:40 Server2.horn amavis-maiad[18408]: Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^({ <-- HERE }/)?\*\z/ at (eval 109) line 371.
Oct 15 12:29:40 Server2.horn amavis-maiad[18408]: Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^({ <-- HERE }/)?\*\z/ at (eval 109) line 374.
Oct 15 12:29:40 Server2.horn amavis-maiad[18408]: amavisd-maia.
Oct 15 12:29:40 Server2.horn systemd[1]: Started LSB: Starts amavisd-maia maiad mailfilter.

**Comment by Mofred1** [comment]
Found it:
line 304 is actually 13746
-      $query =~ s[ ({}/)? \* ][ $1 eq '' ? $f : "$tempdir/parts/$f" ]gesx;
+     $query =~ s[ (\{\}/)? \* ][ $1 eq '' ? $f : "$tempdir/parts/$f" ]gesx;
line 371 is 13813
-    if (grep { m{^({}/)?\*\z} } @args) {    #  {}/* or *, list each file
+   if (grep { m{^(\{\}/)?\*\z} } @args) {    #  {}/* or *, list each file
line 374 is 13616
-      @args = map { !m{^({}/)?\*\z} ? $_
+      @args = map { !m{^(\{\}/)?\*\z} ? $_

**Comment by technion** [comment]
I don't have a relevant system to test with but feel free to send a PR.

**Comment by uttendorfskyp** [comment]
I want to confirm, that changes from @Mofred1 work fine, tested on FreeBSD 12.1-RELEASE

**Comment by technion** [comment]
Fixed in PR from @uttendorfskyp
