### ISSUE TITLE
Theme error on login page */maia/login.php

### ISSUE THREAD

**Issue by joh-ku** [technion/maia_mailguard#83]
Hi Folks,
this is a question not an issue, but i don't no where else i could ask for help.
My installation seems all good, the config check under `*/maia/admin/configtest.php` states all good as well, but when i try to enter maia under `*/maia/login.php` i get the following error:
`Error with themes: theme not found or permissions problem.`

I don't have any further error or information via logs etc. as there is nothing. I've no clue what's the issue here. The themes folder `*/maia/themes/` seems to have all the right privileges:

```
total 26
-rw-r--r--  1 www  www  31 Mar 26 07:19 .htaccess
drwxr-xr-x  8 www  www   9 Dec  2  2018 desert_sand
drwxr-xr-x  7 www  www   8 Dec  2  2018 dgm
drwxr-xr-x  8 www  www   9 Dec  2  2018 ocean_surf
```

Has anybody a hint for me on how to resolve this error?

Best regards
joh-ku

**EDIT:**

Installation is on a FreeBSD server (FreeBSD 12.1-RELEASE-p3 GENERIC  amd64) with the current `security/maia` port.

**Comment by joh-ku** [comment]
I figured out that the error message is returned in `maia/smarty.php` and that `$path` in this context is an empty string if this is of any help...

```
if (! (is_dir(dirname(__FILE__)."/themes/$path") && is_dir(dirname(__FILE__)."/themes/$path/templates") && is_readable(dirname(__FILE__)."/themes/$path/templates"))) {
        exit($lang['error_themes'];
}
```

**Comment by joh-ku** [comment]
Alright, i figured it out. The `maia-mysql.sql` script is faulty. When executing the initialization part at the bottom of this script, the insert operation fails at this line (and many more afterwards) https://github.com/technion/maia_mailguard/blob/master/maia-mysql.sql#L716.

As a consequence of this abortion, the table `maia_themes` is left empty and the login page cannot be displayed.

**Comment by greenblind** [comment]
> Alright, i figured it out. The `maia-mysql.sql` script is faulty (at least with default encoding). When executing the initialization part at the bottom of this script, the insert operation fails at this line (and many more afterwards) https://github.com/technion/maia_mailguard/blob/master/maia-mysql.sql#L716.
> 
> As a consequence of this abortion, the table `maia_themes` is left empty and the login page cannot be displayed.

You have saved my headcache! I just got tired of setting maia up on fbsd. thanks!
